---
title: "3. Genomic analysis"
output: word_document
date: "2023-12-10"
---


# Clear workspace and set directory
```{r setup}
knitr::opts_knit$set(root.dir=normalizePath("~/GitHub/Bifidobacterium"))
#setwd("~/GitHub/Bifidobacterium")
getwd()
rm(list=ls())
```

# Load packages and functions
```{r}
getwd()
require("ggplot2");require("tidyverse");require("png");require("dplyr");require("grid");require("vegan");require("indicspecies");require("ggrepel");require("gridExtra")
```

# Load data
```{r}
mycols=c('black','black','black')
mutpopdf<- read.csv("~/GitHub/Bifidobacterium/Pipeline/2_Excel_/cases_signif.muts.per.pop.csv")
gxp.all.raw <- read.csv("~/GitHub/Bifidobacterium/Pipeline/3_Python/Outputs/Bifidobacterium_labels_gxp.csv")#<-- can do ordination analysis with ALL mutations in ALL genes
# <- read.csv("~/GitHub/Bifidobacterium/Pipeline/3_Python/Bifidobacterium_labels_gxp_fixed.only.csv")#<-- can do ordination with all FIXED mutations in ALL genes
gxp.signif.raw <- read.csv("~/GitHub/Bifidobacterium/Pipeline/3_Python/Outputs/Bifidobacterium_labels_gxp_signif.genes.only.csv")
gxp.signif.raw$sample <- as.factor(gxp.signif.raw$sample)
gxp.signif.raw$treatment <- as.factor(gxp.signif.raw$treatment)
levels(gxp.signif.raw$treatment)[levels(gxp.signif.raw$treatment)=="F"] <- "DP0"
levels(gxp.signif.raw$treatment)[levels(gxp.signif.raw$treatment)=="P"] <- "DP5"
levels(gxp.signif.raw$treatment)[levels(gxp.signif.raw$treatment)=="X"] <- "DP24"
gxp.signif <- as_tibble(gxp.signif.raw)
gxp.signif <- as.matrix(gxp.signif[,3:ncol(gxp.signif)])

gxp.all.raw$sample <- as.factor(gxp.all.raw$sample)
gxp.all.raw$treatment <- as.factor(gxp.all.raw$treatment)
levels(gxp.all.raw$treatment)[levels(gxp.all.raw$treatment)=="F"] <- "DP0"
levels(gxp.all.raw$treatment)[levels(gxp.all.raw$treatment)=="P"] <- "DP5"
levels(gxp.all.raw$treatment)[levels(gxp.all.raw$treatment)=="X"] <- "DP24"
gxp.all <- as_tibble(gxp.all.raw)
gxp.all <- as.matrix(gxp.all[,3:ncol(gxp.all)])
```

```{r}
#First, let's ask whether the number of mutns in significant genes differs among the diet treatments

mutpopaov<-aov(mutpopdf$num.muts ~ mutpopdf$Evolution_treatment)
summary(mutpopaov)
#Not signif. Same number of mutns for all the strains
#TukeyHSD(mutpopaov)


gxp.signif.adonis <- adonis(gxp.signif ~ gxp.signif.raw$treatment, method = "bray", permutations = 9999)
#############NEED TO UPDATE THE BELOW INFO
#                          Df  SumsOfSqs MeanSqs F.Model    R2  Pr(>F)    
#gxp.signif.raw$treatment  2    1.6067 0.80334   3.596 0.25511  1e-04 ***
#Residuals                21    4.6914 0.22340         0.74489           
#Total                    23    6.2981                 1.00000      
#

#:


# Create a distance matrix
gxp.signif.dist <- vegdist(gxp.signif, method = 'bray', upper = TRUE, diag = TRUE)
gxp.signif.dist <- as_tibble(data.matrix(gxp.signif.dist))

# Run PCoA and quantify explained variance
pcoa.eig <- cmdscale(gxp.signif.dist, eig = TRUE, k = 3)
explainvar1 <- round(pcoa.eig$eig[1] / sum(pcoa.eig$eig), 3) * 100 # 29.8 %
explainvar2 <- round(pcoa.eig$eig[2] / sum(pcoa.eig$eig), 3) * 100 # 17.1 %
explainvar3 <- round(pcoa.eig$eig[3] / sum(pcoa.eig$eig), 3) * 100 # 16.3 %
sum.eig <- sum(explainvar1, explainvar2, explainvar3) # 54 %

# Add sample and treatment IDs
gxp.signif.pcoa <- as.data.frame(pcoa.eig[1])
gxp.signif.pcoa$treatment <- gxp.signif.raw$treatment
row.names(gxp.signif.pcoa) <- gxp.signif.raw$sample
gxp.signif.pcoa$sample <- gxp.signif.raw$sample
names(gxp.signif.pcoa)[1:3] <- c('PCo1', 'PCo2', 'PCo3')
```

# Plotting PCoA
```{r}
################################################################################

################################################################################
png(filename="~/GitHub/Bifidobacterium/Pipeline/3_Python/pcoa.test8_signif.only.hulls.png",
    width = 1200, height = 1200, res = 96*2) 

plot.new()
par(mar = c(7, 7, 5, 7))

plot(gxp.signif.pcoa[ ,1], gxp.signif.pcoa[ ,2],
     ylim = c(-.75, .75), xlim = c(-0.75, 0.75),
     xlab = "", ylab = "", xaxt = "n", yaxt = "n",
     pch = 22, cex = 2.0, type = "n", cex.lab = 1.5, cex.axis = 1,
     axes = FALSE)

# Add axes
axis(side = 2, lwd.ticks = 2, cex.axis = 1.25, las = 1,
     labels = c("-1.0", "-0.5", "0.0", "0.5", "1.0"), at = c(-1, -0.5, 0, 0.5, 1))
#axis(side = 4, lwd.ticks = 2, cex.axis = 1.25, las = 1,
#     at=c(-1, -0.5, 0, 0.5, 1), labels = F)
axis(side = 1, lwd.ticks = 2, cex.axis = 1.25, las = 1,
     labels = c("-0.5", "0.0", "0.5"), at = c(-0.5, 0, 0.5))
#axis(side = 3, lwd.ticks = 2, cex.axis = 1.25, las = 1,
#     at = c(-0.5, 0, 0.5), labels = F)
abline(h = 0, v = 0, lty = 3)
box(lwd = 2)

# Add axis labels
mtext(expression(paste("PCo 1 (29.8 %)", sep = "")), side = 1,
      outer = TRUE, cex = 1.5, line = -3.0)
mtext(expression(paste("PCo 2 (17.1 %)", sep = "")), side = 2,
      outer = TRUE, cex = 1.5, line = -3.0)

# Plot points by strain
points(essent.F[ ,1], essent.F[ ,2], pch = 21,
       cex = 1, col = "blue", bg = "blue", lwd = 2)

points(essent.P[ ,1], essent.P[ ,2], pch = 21,
       cex = 1, col = "red", bg = "red", lwd = 2)   

points(essent.X[ ,1], essent.X[ ,2], pch = 21,
       cex = 1, col = "dark grey", bg = "dark grey", lwd = 2)  

# Add ellipses col = c("blue","red","dark grey"), 
ordihull(cbind(gxp.signif.pcoa$PCo1, gxp.signif.pcoa$PCo2), groups=gxp.signif.pcoa$treatment, lwd=2, lty=0, draw = "polygon", col = c("blue","red","dark grey"), label = TRUE)

#ordiellipse(cbind(gxp.signif.pcoa$PCo1, gxp.signif.pcoa$PCo2), groups=gxp.signif.pcoa$treatment,kind = "sd", conf = 0.95, lwd = 2, lty = 3, draw = "polygon", col = c("blue","red","dark grey"), label = TRUE)

# Subset PCoA scores by strain
essent.F <- gxp.signif.pcoa[which(gxp.signif.pcoa$treatment == "DP0"), ]
essent.P <- gxp.signif.pcoa[which(gxp.signif.pcoa$treatment == "DP5"), ]
essent.X <- gxp.signif.pcoa[which(gxp.signif.pcoa$treatment == "DP24"), ]

 

# Add P-value associated with PERMANOVA
#mtext(expression(~italic("P")~"= 0.0001"), line = -1.75, cex = 1.0, at = -0.4)

# Add treatment labels
#mtext("F", line = -19, cex = 1.2, at = -0.3)
#mtext("G-F5", line = -19, cex = 1.2, at = 0.3)
#mtext("G-F24", line = -19, cex = 1.2, at = 0.3)

# Close Plot Device
dev.off()
graphics.off()

# Show Plot
img <- readPNG("~/GitHub/Bifidobacterium/Pipeline/3_Python/pcoa.test8_signif.only.hulls.png")
grid.raster(img)
```


```{r}
################################################################################
#########################Let's look at axis 3##################################
png(filename="~/GitHub/Bifidobacterium/Pipeline/3_Python/pcoa.test9_signif.only.PCo3.png",
    width = 1200, height = 1200, res = 96*2) 

plot.new()
par(mar = c(7, 7, 5, 7))

plot(gxp.signif.pcoa[ ,1], gxp.signif.pcoa[ ,3],
     ylim = c(-.75, .75), xlim = c(-0.75, 0.75),
     xlab = "", ylab = "", xaxt = "n", yaxt = "n",
     pch = 22, cex = 2.0, type = "n", cex.lab = 1.5, cex.axis = 1,
     axes = FALSE)

# Add axes
axis(side = 2, lwd.ticks = 2, cex.axis = 1.25, las = 1,
     labels = c("-1.0", "-0.5", "0.0", "0.5", "1.0"), at = c(-1, -0.5, 0, 0.5, 1))
#axis(side = 4, lwd.ticks = 2, cex.axis = 1.25, las = 1,
#     at=c(-1, -0.5, 0, 0.5, 1), labels = F)
axis(side = 1, lwd.ticks = 2, cex.axis = 1.25, las = 1,
     labels = c("-0.5", "0.0", "0.5"), at = c(-0.5, 0, 0.5))
#axis(side = 3, lwd.ticks = 2, cex.axis = 1.25, las = 1,
#     at = c(-0.5, 0, 0.5), labels = F)
abline(h = 0, v = 0, lty = 3)
box(lwd = 2)

# Add axis labels
mtext(expression(paste("PCo 1 (29.8 %)", sep = "")), side = 1,
      outer = TRUE, cex = 1.5, line = -3.0)
mtext(expression(paste("PCo 3 (16.3 %)", sep = "")), side = 2,
      outer = TRUE, cex = 1.5, line = -3.0)

# Plot points by strain
points(essent.F[ ,1], essent.F[ ,3], pch = 21,
       cex = 1, col = "blue", bg = "blue", lwd = 2)

points(essent.P[ ,1], essent.P[ ,3], pch = 21,
       cex = 1, col = "red", bg = "red", lwd = 2)   

points(essent.X[ ,1], essent.X[ ,3], pch = 21,
       cex = 1, col = "dark grey", bg = "dark grey", lwd = 2)  

# Add ellipses col = c("blue","red","dark grey"), 
ordihull(cbind(gxp.signif.pcoa$PCo1, gxp.signif.pcoa$PCo3), groups=gxp.signif.pcoa$treatment,conf = 0.95, lwd = 2, lty = 0, draw = "polygon", col = c("blue","red","dark grey"), label = TRUE)

#ordiellipse(cbind(gxp.signif.pcoa$PCo1, gxp.signif.pcoa$PCo2), groups=gxp.signif.pcoa$treatment,kind = "sd", conf = 0.95, lwd = 2, lty = 3, draw = "polygon", col = c("blue","red","dark grey"), label = TRUE)

# Subset PCoA scores by strain
essent.F <- gxp.signif.pcoa[which(gxp.signif.pcoa$treatment == "DP0"), ]
essent.P <- gxp.signif.pcoa[which(gxp.signif.pcoa$treatment == "DP5"), ]
essent.X <- gxp.signif.pcoa[which(gxp.signif.pcoa$treatment == "DP24"), ]



# Add P-value associated with PERMANOVA
#mtext(expression(~italic("P")~"= 0.0001"), line = -1.75, cex = 1.0, at = -0.4)

# Add treatment labels
#mtext("F", line = -19, cex = 1.2, at = -0.3)
#mtext("G-F5", line = -19, cex = 1.2, at = 0.3)
#mtext("G-F24", line = -19, cex = 1.2, at = 0.3)

# Close Plot Device
dev.off()
graphics.off()

# Show Plot
img <- readPNG("~/GitHub/Bifidobacterium/Pipeline/3_Python/pcoa.test9_signif.only.PCo3.png")
grid.raster(img)
```


```{r}
################################################################################
################################################################################
# Analysis of variation among populations (beta diversity) within each diet treatment.
# Are there differences in composition variance between the treatments?
################################################################################
gd <- vegdist(gxp.signif, method = 'bray', upper = TRUE, diag = TRUE)
compare.variance <- betadisper(d=gd, group = c("F","F","F","F","F","F","F","F","G-F5","G-F5","G-F5","G-F5","G-F5","G-F5","G-F5","G-F5","G-F24","G-F24","G-F24","G-F24","G-F24","G-F24","G-F24","G-F24"))
c.v.result <- anova(compare.variance)
c.v.result
TukeyHSD(compare.variance)
###Significant difference in the amount of variance, i.e. beta diversity, among the treatments. F has more beta diversity than G-F5 or G-F24 do
```

# Do indicator gene analysis
```{r}
#
trts.i<- c("F","F","F","F","F","F","F","F","G-F5","G-F5","G-F5","G-F5","G-F5","G-F5","G-F5","G-F5","G-F24","G-F24","G-F24","G-F24","G-F24","G-F24","G-F24","G-F24")
gxp.i<-gxp.signif
indvals = multipatt(x=gxp.i, cluster=trts.i,func="IndVal.g", control = how(nperm=999))
summary(indvals, indvalcomp = TRUE)
#Component A: "specificity" or "positive predictive value" of the species as indicator of the site group. It is the sample estimate of the probability that the surveyed site belongs to the target site group given the fact that the species has been found.
#Component B: "Fidelity" or "sensitivity" of the species as indicator of the target site group. It is is sample estimate of the probability of finding the species in sites belonging to the site group.

gxpcomb<- combinespecies(gxp.i, max.order = 2)$XC
dim(gxpcomb)
indvalcomb = multipatt(x=gxpcomb, cluster=trts.i, duleg = TRUE,control = how(nperm=999))
summary(indvalcomb, indvalcomp = TRUE)

####This is using the whole matrix instead of specifically the significant genes:
gxpa.i<-gxp.all
indval=multipatt(x=gxpa.i,cluster=trts.i,func="IndVal.g",control=how(nperm=999))
summary(indval,indvalcomp = TRUE)

gxpacomb<- combinespecies(gxpa.i, max.order = 2)$XC
dim(gxpacomb)
#indvalacomb = multipatt(x=gxpacomb, cluster=trts.i, duleg = TRUE,control = how(nperm=999))
#summary(indvalacomb, indvalcomp = TRUE)
#I just commented out the 2 abopve lines so that the whole script runs faster when I run it to declare my variables
```

