---
title: "5. Comparison between two mutated transport proteins for fructose"
output: word_document
date: "2023-12-10"
---


# Clear workspace and set directory
```{r setup}
knitr::opts_knit$set(root.dir=normalizePath("~/GitHub/Bifidobacterium"))
#setwd("~/GitHub/Bifidobacterium")
getwd()
rm(list=ls())
```

# Load packages and functions
```{r}
getwd()
require("ggplot2");require("tidyverse");require("png");require("dplyr");require("grid");require("vegan");require("indicspecies");require("ggrepel");require("gridExtra")
```

# Load data
```{r}
mycols=c('black','black','black')
#Import data from HPLC experiments
myhplc<-read.csv("./Data/metabolite.flux.data.csv")
myhplc$condition_short<-factor(myhplc$condition_short,levels=c("GF","F"))
myhplc$evo_trt<-factor(myhplc$evo_trt,levels=c("F","P","X","Anc"))
myhplc$evo_trt_plotting<-recode(myhplc$evo_trt, "F" = "DP0", "P" = "DP5", "X" = "DP24", "Anc" = "Ancestor")
myhplc$evo_trt_plotting<-factor(myhplc$evo_trt_plotting,levels=c("DP0","DP5","DP24","Ancestor"))

grrPglcU<-read.csv("./Data/umax.on.P_F-evolved_glcU.vs.lacY.csv")
```

```{r}

#Compare glcU mutants (evolved on DP0) to lacY mutants (evolved on DP0) for growth rate when grown on DP5
var.test(x=c(filter(grrPglcU, importer=="glcU")$umax_on_P),y=c(filter(grrPglcU, importer=="lacY")$umax_on_P),ratio=1,alternative = "t")
#P = .05035. Homoscedastic.
t.test(x=c(filter(grrPglcU, importer=="glcU")$umax_on_P),y=c(filter(grrPglcU, importer=="lacY")$umax_on_P),mu=0,alternative = "t",paired=F,var.equal=T)
#p = 0.004283
```

