---
title: "Probiotic evolution"
author: "Roy Moger-Reischer and Jay T. Lennon"
date: "`r format(Sys.time(), '%d %B, %Y')`"
header-includes:
   - \usepackage{array}
output: pdf_document
geometry: margin = 2.54cm
---

# Growth rates of evovled strains on different diets (Fig. 2)

## Clear workspace and set directory

```{r setup}
rm(list=ls())
knitr::opts_knit$set(root.dir=normalizePath("~/GitHub/Bifidobacterium"))
getwd()
```

# Load packages and functions

```{r}
require("png")
require("dplyr")
require("grid")
require("knitr")
require("extrafont")
require("ggrepel");
require("gridExtra")
sem <- function(x) sqrt(var(x)/length(x))
cv <- function(x) (sd(x)/mean(x))*100
```

# Load data
```{r}
grcvdata <- read.csv("~/GitHub/Bifidobacterium/data/growth.curves.anaerobic.csv")
grcvdata$carbon.tech.assay <- factor(grcvdata$carbon.tech.assay, 
            levels = c("F", "G-F5","G-F24","Ancestor"))
grcvdata$carbon.tech.evo <- factor(grcvdata$carbon.tech.evo, 
            levels = c("F", "G-F5","G-F24","Ancestor"))
grcvdata$carbon.plotting.assay <- recode(grcvdata$carbon.tech.assay, 
            "F" = "DP0", "G-F5" = "DP5", "G-F24" = "DP24")
grcvdata$carbon.plotting.evo <- recode(grcvdata$carbon.tech.evo, 
            "F" = "DP0", "G-F5" = "DP5", "G-F24" = "DP24")

# Remove rows with ancestor data
grc.no.anc <- grcvdata %>% 
  filter(carbon.evo != "Ancestor")

grc.no.anc <- grcvdata %>% 
  filter(carbon.evo != "Ancestor")

# Calculate difference data (i.e., umax evolved - umax ancestor) and percent data (i.e., [umax evolved - umax ancestor] / umax ancestor)
grc.all <- grc.no.anc %>%
            mutate(delta.umax = umax - umax.anc, 
            delta.per = (umax - umax.anc)/umax.anc)

# Subset
grc.sub <- grc.all %>% select(umax, umax.anc, carbon.plotting.assay,
            carbon.plotting.evo, delta.umax, delta.per)

colnames(grc.sub) <- c("umax", "umax.anc", "assay.diet", "evo.diet", 
            "delta.umax", "per.umax")

# To more easily interpret interaction matrix from ANOVA
grc <- grc.sub %>% 
            mutate(assay.intx = paste0(assay.diet, "A"), 
            evo.intx = paste0(evo.diet, "E"))

# Calculate delta values: means and SEMs for plotting
delta.umax.sum <- grc %>% group_by(assay.diet, evo.diet) %>%
            summarize(mean = mean(delta.umax), sem = sem(delta.umax))
delta.umax.sum <- delta.umax.sum %>% ungroup()
delta.umax.sum.x <- delta.umax.sum %>% mutate(assay.x = rep(c(1:3), times = 3))
delta.umax.sum <- as.data.frame(delta.umax.sum.x)

# Calculate percent values: means and SEMs for plotting
per.umax.sum <- grc %>% group_by(assay.diet, evo.diet) %>%
            summarize(mean = mean(per.umax), sem = sem(per.umax))
per.umax.sum <- per.umax.sum %>% ungroup()
per.umax.sum.x <- per.umax.sum %>% mutate(assay.x = rep(c(1:3), times = 3))
per.umax.sum <- as.data.frame(per.umax.sum.x)
```

# Statistics 

```{r}
fit1 <- aov(delta.umax ~ assay.intx * evo.intx, data = grc)
summary(fit1)
posthoc <- TukeyHSD(fit1)
comps.delta <- as.data.frame(posthoc[3])
colnames(comps.delta) <- c("dif", "lwr", "upr", "p")

# How did DP24-evolved strain evolve "home" vs. "away"?
DP24E.24v0 <- comps.delta["DP24A:DP24E-DP0A:DP24E",] # p = 0.7622939
DP24E.24v5 <- comps.delta["DP5A:DP24E-DP24A:DP24E",] # p = 0.01287935
DP24E.0v5 <- comps.delta["DP5A:DP24E-DP0A:DP24E",] # p = 0.5328427

# How did DP5-evolved strain evolve "home" vs. "away"?
DP5E.24v0 <- comps.delta["DP24A:DP5E-DP0A:DP5E",] # p = 0.6336117
DP5E.24v5 <- comps.delta["DP5A:DP5E-DP24A:DP5E",] # p = 4.981227e-11
DP5E.0v5 <- comps.delta["DP5A:DP5E-DP0A:DP5E",] # p = 6.3443e-08

# How did DP0-evolved strain evolve "home" vs. "away"?
DP0E.24v0 <- comps.delta["DP24A:DP0E-DP0A:DP0E",] # p = 8.417444e-06
DP0E.24v5 <- comps.delta["DP5A:DP0E-DP24A:DP0E",] # p = 0.012974516
DP0E.0v5 <- comps.delta["DP5A:DP0E-DP0A:DP0E",] # p = 0.4859786

fit2 <- aov(per.umax ~ assay.intx * evo.intx, data = grc)
summary(fit2)
posthoc <- TukeyHSD(fit2)
comps.per <- as.data.frame(posthoc[3])
colnames(comps.per) <- c("dif", "lwr", "upr", "p")

# How did DP24-evolved strain evolve "home" vs. "away"?
DP24E.24v0 <- comps.per["DP24A:DP24E-DP0A:DP24E",] # p = 0.8684085
DP24E.24v5 <- comps.per["DP5A:DP24E-DP24A:DP24E",] # p = 0.521135
DP24E.0v5 <- comps.per["DP5A:DP24E-DP0A:DP24E",] # p = 0.9996507

# How did DP5-evolved strain evolve "home" vs. "away"?
DP5E.24v0 <- comps.per["DP24A:DP5E-DP0A:DP5E",] # p = 0.5488947
DP5E.24v5 <- comps.per["DP5A:DP5E-DP24A:DP5E",] # p = 8.871469e-08
DP5E.0v5 <- comps.per["DP5A:DP5E-DP0A:DP5E",] # p = 0.0001980938

# How did DP0-evolved strain evolve "home" vs. "away"?
DP0E.24v0 <- comps.per["DP24A:DP0E-DP0A:DP0E",] # p = 1.013897e-06
DP0E.24v5 <- comps.per["DP5A:DP0E-DP24A:DP0E",] # p = 0.3453436
DP0E.0v5 <- comps.per["DP5A:DP0E-DP0A:DP0E",] # p = 0.004869201

# Overall, how much did evolution increase fitness?
ttest <- t.test(grc$per.umax, mu = 0, alternative = "two.sided", conf.level = 0.95)
# t = 10.862, df = 71, p-value < 2.2e-16
# 10.6 +/- 0.972 (mean +/- SEM)

# Evolution on DP24 only increased fitness by 4.36 %, independent of diet 
```

# Create interaction plot: change in percent growth rate (Fig. 2)

```{r}
# Arrange data
assay.x <- per.umax.sum$assay.x # Common x-values
DP0.assay <- per.umax.sum$mean[1:3]  # First set of y-values
DP0.assay.sem <- per.umax.sum$sem[1:3]
DP5.assay <- per.umax.sum$mean[4:6]  # Second set of y-values
DP5.assay.sem <- per.umax.sum$sem[4:6]
DP24.assay <- per.umax.sum$mean[7:9]  # Third set of y-values
DP24.assay.sem <- per.umax.sum$sem[7:9]

# Start figures
png(filename="~/GitHub/Bifidobacterium/figures/Fig.2.png",
    width = 1200, height = 1200, res = 96*2) 

#par(mar = c(7, 7, 5, 7))

par(mfrow = c(1, 1),     # 1 row, 1 column
    oma = c(1, 1, 1, 2), # Outer margins (bottom, left, top, right)
    mar = c(7, 7, 5, 7)) # Inner margins for each plot

# Create the initial plot: DP0
plot(assay.x[1:3], DP0.assay, type = "o", col = "tomato1", bg = "tomato1", pch = 21, 
     lwd = 2, cex = 2, yaxt = "n", xaxt = "n", cex.lab = 1.5, las = 1,  
     ylab = "", xlab = "", ylim = c(-1, 27), xlim = c(0.5, 4))
arrows(x0 = assay.x[1:3], y0 = DP0.assay, 
       y1 = DP0.assay + DP0.assay.sem, 
       angle = 90, length = 0.1, lwd = 2, col = "tomato1")
arrows(x0 = assay.x[1:3], y0 = DP0.assay, 
       y1 = DP0.assay - DP0.assay.sem, 
       angle = 90, length = 0.1, lwd = 2, col = "tomato1")

# Add the second line: DP5
lines(assay.x[4:6], DP5.assay, type = "o", col = "springgreen4", 
      bg = "springgreen4", pch = 21, cex = 2, lwd = 2)
arrows(x0 = assay.x[4:6], y0 = DP5.assay, 
       y1 = DP5.assay + DP5.assay.sem, 
       angle = 90, length = 0.1, lwd = 2, col = "springgreen4")
arrows(x0 = assay.x[4:6], y0 = DP5.assay, 
       y1 = DP5.assay - DP5.assay.sem, 
       angle = 90, length = 0.1, lwd = 2, col = "springgreen4")

# Add the third line: DP24
lines(assay.x[7:9], DP24.assay, type = "o", col = "cornflowerblue", 
      bg = "cornflowerblue", pch = 21, cex = 2, lwd = 2)
arrows(x0 = assay.x[7:9], y0 = DP24.assay, 
       y1 = DP24.assay + DP24.assay.sem, 
       angle = 90, length = 0.1, lwd = 2, col = "cornflowerblue")
arrows(x0 = assay.x[7:9], y0 = DP24.assay, 
       y1 = DP24.assay - DP24.assay.sem, 
       angle = 90, length = 0.1, lwd = 2, col = "cornflowerblue")

box(lwd=2)

# Add axes and labels
axis(side = 2, lwd.ticks = 2, cex.axis = 1.25, las = 1,
     labels = c("0", "5", "10", "15", "20", "25", "30"), 
     at = c(0, 5, 10, 15, 20, 25, 30))
axis(side = 4, lwd.ticks = 2, cex.axis = 1.25, las = 1,
     at=c(0, 5, 10, 15, 20, 25, 30), labels = F)
axis(side = 3, lwd.ticks = 2, cex.axis = 1.25, las = 1,
     at = c(1, 2, 3), labels = F)
axis(side = 1, lwd.ticks = 2, cex.axis = 1.25, las = 1,
     labels = c("DP0", "DP5", "DP24"), 
     col.axis = "black", at = c(1, 2, 3))

mtext(expression('Resource size (assay)'), side = 1,
      outer = TRUE, cex = 1.5, line = -2.5, adj = 0.5)
mtext(expression(Delta~'fitness (%)'), side = 2, outer = TRUE, 
      cex = 1.5, line = -3, adj = 0.55)

# Add white box on y axis
xleft <- 3.8   # Left edge (outside the main plot)
ybottom <- 8 # Bottom edge (within the main plot)
xright <- 4.5   # Right edge (within the main plot)
ytop <- 11    # Top edge (within the main plot)

# Add solid white rectangle
rect(xleft, ybottom, xright, ytop, col = "white", border = "white", xpd = TRUE)

# Add evolution labels
mtext("Resource size", side = 3, line = -11, cex = 1.3, at = 5.4, col = "black")
mtext("(evolution)", side = 3, line = -12, cex = 1.3, at = 5.4, col = "black")
segments(3.95, 9.5, 4.4, 9.5, col = "grey75", lwd = 2, xpd = NA, lty = 1)
segments(3.95, 4, 3.95, 13.5, col = "grey75", lwd = 2, xpd = NA, lty = 1)
segments(3.7, 13.5, 3.95, 13.5, col = "grey75", lwd = 2, xpd = NA, lty = 1)
segments(3.7, 4, 3.95, 4, col = "grey75", lwd = 2, xpd = NA, lty = 1)
text(3.5, 9.75, labels = "DP0", cex = 1.3, col = "tomato1")
text(3.5, 12, labels = "DP5", cex = 1.3, col = "springgreen4")
text(3.5, 5.5, labels = "DP24", cex = 1.3, col = "cornflowerblue")

# Add significance letters
text(0.8, DP0.assay[1]*0.95, labels = "b", cex = 1, col = "tomato1")
text(1.8, DP0.assay[2]*0.9, labels = "a", cex = 1, col = "tomato1")
text(2.8, DP0.assay[3]*0.85, labels = "a", cex = 1, col = "tomato1")

text(0.8, DP5.assay[1]*0.9, labels = "a", cex = 1, col = "springgreen4")
text(1.8, DP5.assay[2]*1, labels = "b", cex = 1, col = "springgreen4")
text(2.8, DP5.assay[3]*0.95, labels = "a", cex = 1, col = "springgreen4")

text(0.8, DP24.assay[1]*0.95, labels = "a", cex = 1, col = "cornflowerblue")
text(1.8, DP24.assay[2]*0.80, labels = "a", cex = 1, col = "cornflowerblue")
text(2.8, DP24.assay[3]*0.70, labels = "b", cex = 1, col = "cornflowerblue")

# Close Plot Device
dev.off()
graphics.off()

# Show Plot
img <- readPNG("~/GitHub/Bifidobacterium/figures/Fig.2.png")
grid.raster(img)
```


# Create interaction plot: delta growth rate (Fig. 2a)

```{r}
# Arrange data
assay.x <- delta.umax.sum$assay.x # Common x-values
DP0.assay <- delta.umax.sum$mean[1:3]  # First set of y-values
DP0.assay.sem <- delta.umax.sum$sem[1:3]
DP5.assay <- delta.umax.sum$mean[4:6]  # Second set of y-values
DP5.assay.sem <- delta.umax.sum$sem[4:6]
DP24.assay <- delta.umax.sum$mean[7:9]  # Third set of y-values
DP24.assay.sem <- delta.umax.sum$sem[7:9]

# Start figures
png(filename="~/GitHub/Bifidobacterium/figures/Fig.2a.png",
    width = 1200, height = 1200, res = 96*2) 

par(mar = c(7, 7, 5, 7))

# Create the initial plot: DP0
plot(assay.x[1:3], DP0.assay, type = "o", col = "tomato1", bg = "tomato1", pch = 21, 
     lwd = 2, cex = 2, yaxt = "n", xaxt = "n", cex.lab = 1.5, las = 1,  
     ylab = "", xlab = "", ylim = c(-0.01, 0.22), xlim = c(0.5, 4))
arrows(x0 = assay.x[1:3], y0 = DP0.assay, 
       y1 = DP0.assay + DP0.assay.sem, 
       angle = 90, length = 0.1, lwd = 2, col = "tomato1")
arrows(x0 = assay.x[1:3], y0 = DP0.assay, 
       y1 = DP0.assay - DP0.assay.sem, 
       angle = 90, length = 0.1, lwd = 2, col = "tomato1")

# Add the second line: DP5
lines(assay.x[4:6], DP5.assay, type = "o", col = "springgreen4", 
      bg = "springgreen4", pch = 21, cex = 2, lwd = 2)
arrows(x0 = assay.x[4:6], y0 = DP5.assay, 
       y1 = DP5.assay + DP5.assay.sem, 
       angle = 90, length = 0.1, lwd = 2, col = "springgreen4")
arrows(x0 = assay.x[4:6], y0 = DP5.assay, 
       y1 = DP5.assay - DP5.assay.sem, 
       angle = 90, length = 0.1, lwd = 2, col = "springgreen4")

# Add the third line: DP24
lines(assay.x[7:9], DP24.assay, type = "o", col = "cornflowerblue", 
      bg = "cornflowerblue", pch = 21, cex = 2, lwd = 2)
arrows(x0 = assay.x[7:9], y0 = DP24.assay, 
       y1 = DP24.assay + DP24.assay.sem, 
       angle = 90, length = 0.1, lwd = 2, col = "cornflowerblue")
arrows(x0 = assay.x[7:9], y0 = DP24.assay, 
       y1 = DP24.assay - DP24.assay.sem, 
       angle = 90, length = 0.1, lwd = 2, col = "cornflowerblue")

box(lwd=2)

# Add axes and labels
axis(side = 2, lwd.ticks = 2, cex.axis = 1.25, las = 1,
     labels = c("0.0", "0.10", "0.20"), at = c(0, 0.1, 0.2))
axis(side = 4, lwd.ticks = 2, cex.axis = 1.25, las = 1,
     at=c(0, 0.1, 0.2), labels = F)
axis(side = 3, lwd.ticks = 2, cex.axis = 1.25, las = 1,
     at = c(1, 2, 3), labels = F)
axis(side = 1, lwd.ticks = 2, cex.axis = 1.25, las = 1,
     labels = c("DP0", "DP5", "DP24"), 
     col.axis = "black", at = c(1, 2, 3))
mtext(expression('Assay diet'), side = 1,
      outer = TRUE, cex = 1.5, line = -3.5, adj = 0.45)
mtext(expression(Delta~'Maximum growth rate (d'^-1*')'), side = 2, outer = TRUE, 
      cex = 1.5, line = -3, adj = 0.55)

# Add evolution labels
text(3.5, 0.16, labels = "Evolution", cex = 1.3, col = "black")
text(3.5, 0.145, labels = "diet:", cex = 1.3, col = "black")
segments(3.2, 0.135, 3.8, 0.135, col = "black", lwd = 1.5, xpd = NA)
text(3.5, 0.07, labels = "DP0", cex = 1.3, col = "tomato1")
text(3.5, 0.115, labels = "DP5", cex = 1.3, col = "springgreen4")
text(3.5, 0.035, labels = "DP24", cex = 1.3, col = "cornflowerblue")

# Close Plot Device
dev.off()
graphics.off()

# Show Plot
img <- readPNG("~/GitHub/Bifidobacterium/figures/Fig.2a.png")
grid.raster(img)
```