---
title: "4. Metabolite flux"
output: word_document
date: "2023-12-10"
---


# Clear workspace and set directory
```{r setup}
knitr::opts_knit$set(root.dir=normalizePath("~/GitHub/Bifidobacterium"))
#setwd("~/GitHub/Bifidobacterium")
getwd()
rm(list=ls())
```

# Load packages and functions
```{r}
getwd()
require("ggplot2");require("tidyverse");require("png");require("dplyr");require("grid");require("vegan");require("indicspecies");require("ggrepel");require("gridExtra")
```

# Load data
```{r}
mycols=c('black','black','black')
mycols_breakout=c('black','black','black','black','black','black','black','black')
#Import data from HPLC experiments
myhplc<-read.csv("./Data/metabolite.flux.data.csv")
myhplc$condition_short<-factor(myhplc$condition_short,levels=c("GF","F"))
myhplc$evo_trt<-factor(myhplc$evo_trt,levels=c("F","P","X","Anc"))
myhplc$evo_trt_plotting<-recode(myhplc$evo_trt, "F" = "DP0", "P" = "DP5", "X" = "DP24", "Anc" = "Ancestor")
myhplc$evo_trt_plotting<-factor(myhplc$evo_trt_plotting,levels=c("DP0","DP5","DP24","Ancestor"))


```

# Do statistics
# Can move all references to GF xpt to the 99.everything.else.Rmd file; data from that xpt will not be used in the text that is submitted for publication

```{r}
#####3b#########################################################################
#Importantly, can we detect an increase in fructose import rate of the evolved bacteria, relative to the ancestor?

#First, I need to calculate the average fructose import rate by the ancestor and use it as my mu value for 1-sample t-tests.
anc.flux.fru_F<-mean(c(filter(myhplc, condition_short=="F",evo_trt=="Anc")$flux.fru.pos))

#F evolved vs. ancestor
t.test(x=c(filter(myhplc, condition_short=="F",evo_trt=="F")$flux.fru.pos),mu=anc.flux.fru_F,alternative = "g")
hplcp3.8<-t.test(x=c(filter(myhplc, condition_short=="F",evo_trt=="F")$flux.fru.pos),mu=anc.flux.fru_F,alternative = "g")$p.value
#P < .05. F import after evolution is significantly higher in the absence of glucose.
#FDR: 0.005412862 

#DP5 evolved vs. ancestor
t.test(x=c(filter(myhplc, condition_short=="F",evo_trt=="P")$flux.fru.pos),mu=anc.flux.fru_F,alternative = "g")
hplcp3.9<-t.test(x=c(filter(myhplc, condition_short=="F",evo_trt=="P")$flux.fru.pos),mu=anc.flux.fru_F,alternative = "g")$p.value
#P = 0.1165 F import after evolution is NOT significantly higher in the absence of glucose than that of the ancestor in the absence of glucose.
#THIS MAKES SENSE. DP5 can be imported directly. Meanwhile, DP24 pops are surviving on the dregs of degraded molecules.
#FDR: 0.139784891 

#DP24 evolved vs. ancestor
t.test(x=c(filter(myhplc, condition_short=="F",evo_trt=="X")$flux.fru.pos),mu=anc.flux.fru_F,alternative = "g")
hplcp3.10<-t.test(x=c(filter(myhplc, condition_short=="F",evo_trt=="X")$flux.fru.pos),mu=anc.flux.fru_F,alternative = "g")$p.value
#P < .05. F import after evolution is significantly higher in the absence of glucose.
#FDR: 0.004927588

hplcpvec3b<-c(hplcp3.8,hplcp3.9,hplcp3.10)
hplcpvec3b.adjust<-p.adjust(p=hplcpvec3b, method = "BH")#cite BH&Y 2009
hplcpvec3b
hplcpvec3b.adjust
#0.002706431 0.116487409 0.002463794
```


```{r}
######4#########################################################################
#Do the evolved populations differ in their fructose import rates (in the presence of F alone)?
hplc4.1df<-filter(myhplc,condition_short=="F",evo_trt!="Anc")
hplc4.1aov<-aov(hplc4.1df$flux.fru.pos ~ hplc4.1df$evo_trt)
summary(hplc4.1aov)
TukeyHSD(hplc4.1aov)
#Tukey letters: F: A  DP5: B  DP24: A,B
#Interpretation: F pops were selected to import fructose. DP5 pops were selected to import short oligomers. This likely improved the function of lacY for importing oligomers, but the kinds of mutations that fixed were significantly less beneficial for importing fructose than those that fixed in the fructose-evolved populations. DP24 populations are somewhere intermediate. They're likely surviving on scraps of degraded big oligomers, which prolly includes both small oligomers and monomers.
#Padj values from Tukey HSD:
#P-F 0.0247383
#X-F 0.5942214
#X-P 0.1725517

```


```{r}
######5#########################################################################
#Now I want to compare the fructose import rate between fructose-evolved populations that have LacY mutations to fructose-evolved pops that have GlcU mutations
var.test(x=c(filter(myhplc, condition_short=="F",evo_trt=="F",Importer=="lacY")$flux.fru.pos),y=c(filter(myhplc, condition_short=="F", evo_trt=="F",Importer=="glcU")$flux.fru.pos),ratio=1,alternative = "t")
#P = .1623. Homoscedastic.
t.test(x=c(filter(myhplc, condition_short=="F",evo_trt=="F",Importer=="lacY")$flux.fru.pos),y=c(filter(myhplc, condition_short=="F", evo_trt=="F",Importer=="glcU")$flux.fru.pos),mu=0,alternative = "t",paired=F,var.equal=T)
mean(c(filter(myhplc, condition_short=="F",evo_trt=="F",Importer=="lacY")$flux.fru.pos))
mean(c(filter(myhplc, condition_short=="F",evo_trt=="F",Importer=="glcU")$flux.fru.pos))
#P = 0.006563. F import is higher for the populations with lacY mutations than for those with glcU mutations (14.51 fmol/cell/hr vs 7.43 fmol/cell/hr)
```


```{r}
##########6#####################################################################
#Next, I'll ask whether evolved bacteria have a higher flux of lact and ace production than the ancestor.

#Does lactate production increase after evolution?
anc.flux.lact_F<-mean(c(filter(myhplc, condition_short=="F",evo_trt=="Anc")$flux.lact.0))

#F evolved vs. ancestor
t.test(x=c(filter(myhplc, condition_short=="F",evo_trt=="F")$flux.lact.0),mu=anc.flux.lact_F,alternative = "g")
#P = 0.0132. Lact export after evolution is significantly higher.
#FDR: 1.584397e-02

#DP5 evolved vs. ancestor
t.test(x=c(filter(myhplc, condition_short=="F",evo_trt=="P")$flux.lact.0),mu=anc.flux.lact_F,alternative = "g")
#P = 0.003382. Lact export after evolution is significantly higher.
#FDR: 3.382046e-02

#DP24 evolved vs. ancestor
t.test(x=c(filter(myhplc, condition_short=="F",evo_trt=="X")$flux.lact.0),mu=anc.flux.lact_F,alternative = "g")
#P = 0.001789. Lact export after evolution is significantly higher.
#FDR: 2.684201e-03

####
#Now, does acetate production increase after evolution?
anc.flux.ace_F<-mean(c(filter(myhplc, condition_short=="F",evo_trt=="Anc")$flux.ace.0))

#F evolved vs. ancestor
t.test(x=c(filter(myhplc, condition_short=="F",evo_trt=="F")$flux.ace.0),mu=anc.flux.ace_F,alternative = "g")
#P = 0.0009068. Ace export after evolution is significantly higher in F cdtn.
#FDR: 1.639248e-02 

#DP5 evolved vs. ancestor
t.test(x=c(filter(myhplc, condition_short=="F",evo_trt=="P")$flux.ace.0),mu=anc.flux.ace_F,alternative = "g")
#P = 0.01672. Ace export after evolution is significantly higher in F cdtn.
#FDR: 3.579952e-02 

#DP24 evolved vs. ancestor
t.test(x=c(filter(myhplc, condition_short=="F",evo_trt=="X")$flux.ace.0),mu=anc.flux.ace_F,alternative = "g")
#P = 0.0007976. Ace export after evolution is significantly higher in F cdtn.
#FDR: 2.793390e-03

hplcpvec6.2lac<-c(t.test(x=c(filter(myhplc, condition_short=="F",evo_trt=="F")$flux.lact.0),mu=anc.flux.lact_F,alternative = "g")$p.value,t.test(x=c(filter(myhplc, condition_short=="F",evo_trt=="P")$flux.lact.0),mu=anc.flux.lact_F,alternative = "g")$p.value,t.test(x=c(filter(myhplc, condition_short=="F",evo_trt=="X")$flux.lact.0),mu=anc.flux.lact_F,alternative = "g")$p.value)
hplcpvec6.2.adjustlac<-p.adjust(p=hplcpvec6.2lac, method = "BH")#cite BH&Y 2009
hplcpvec6.2lac
hplcpvec6.2.adjustlac
# 0.020490597 0.035799524 0.005586781

hplcpvec6.2ace<-c(t.test(x=c(filter(myhplc, condition_short=="F",evo_trt=="F")$flux.ace.0),mu=anc.flux.ace_F,alternative = "g")$p.value,t.test(x=c(filter(myhplc, condition_short=="F",evo_trt=="P")$flux.ace.0),mu=anc.flux.ace_F,alternative = "g")$p.value,t.test(x=c(filter(myhplc, condition_short=="F",evo_trt=="X")$flux.ace.0),mu=anc.flux.ace_F,alternative = "g")$p.value)
hplcpvec6.2.adjustace<-p.adjust(p=hplcpvec6.2ace, method = "BH")#cite BH&Y 2009
hplcpvec6.2ace
hplcpvec6.2.adjustace
# 0.002958924 0.054893880 0.002958924
```


```{r}
#####7##########################################################################
#Last, we'll ask whether lact and ace fluxes are differ depending on the evolution treatment. So, 2 ANOVAs (2 metabolites).

#Now we'll compare the evolved populations' abilities to produce lactate when the carbon source is fructose alone. Expectation would be that DP5 populations would be at even more of disadvantage now.
hplc7.2df<-filter(myhplc,condition_short=="F",evo_trt!="Anc")
hplc7.2aov<-aov(hplc7.2df$flux.lact.0 ~ hplc7.2df$evo_trt)
summary(hplc7.2aov)
TukeyHSD(hplc7.2aov)
#However, there are actually now no signif differences. ANOVA P = 0.255


#Now we'll compare the evolved populations' abilities to produce lactate when the carbon source is fructose alone. Expectation would be that non-F populations would be at even more of disadvantage now.
hplc7.4df<-filter(myhplc,condition_short=="F",evo_trt!="Anc")
hplc7.4aov<-aov(hplc7.4df$flux.ace.0 ~ hplc7.4df$evo_trt)
summary(hplc7.4aov)
TukeyHSD(hplc7.4aov)
#However, there are actually now no signif differences. ANOVA P = 0.078, and all Tukey HSD Padj values > 0.1

```
# Make plots
```{r}
hlpc.colors<-c("darkgrey","darkgrey","darkgrey","darkgrey","darkgrey","darkgrey","darkgrey","darkgrey","darkgrey","darkgrey","darkgrey","darkgrey","darkgrey","darkgrey","darkgrey","darkgrey","darkgrey","darkgrey","darkgrey","darkgrey","darkgrey","darkgrey","darkgrey","darkgrey")

hplcdataFall<-filter(myhplc, condition_short=="F")
hplcdataF<-filter(myhplc, condition_short=="F", evo_trt!="Anc")
hplcdataF$evo_trt_plotting<-droplevels(hplcdataF$evo_trt_plotting)
```


# WORK HERE ART H
# Make Fig. 4
```{r}
hplclactplot_F <- ggplot(hplcdataF, aes(x=evo_trt_plotting, y=flux.lact.0))
###
hplclactpanel_F <- hplclactplot_F + geom_jitter(aes(shape = evo_trt_plotting, color = evo_trt_plotting), position = position_jitterdodge(jitter.width = 0.8, dodge.width = 0.7), size = 5.5, stroke = 2) +
  #geom_errorbar(data=grcvdataF, mapping = aes(x=carbon.tech.evo,ymin=umax.anc,ymax=umax.anc),color=grcv.colors,lwd=2.2,linetype=117) +
  geom_hline(yintercept = mean(filter(myhplc, condition_short=="F", evo_trt_plotting=="Ancestor")$flux.lact.0), color="dark grey", lwd=2.2,linetype=117) +
  scale_shape_manual(values = c(0,0,0)) +#12 is a square with a vertical cross inside it
    stat_summary(
    aes(color = evo_trt_plotting),
    fun.data = "mean_se", fun.args = list(mult = (0)), #mean_sdl add +/- standard deviation; mult=1 means that it is SD*1 that is drawn.  Mean_se draws the standard error of the mean
    geom = "point", size = 10, stroke=2, shape=16,
    position = position_dodge(1),
  ) +
  stat_summary(
    aes(color = evo_trt_plotting),
    fun.data = "mean_se", fun.args = list(mult = (1)), #mean_sdl add +/- standard deviation; mult=1 means that it is SD*1 that is drawn.  Mean_se draws the standard error of the mean
    geom = "linerange", size = 3,
    position = position_dodge(1),
  ) +
  scale_color_manual(values = mycols_breakout) +
  scale_y_continuous(limits = c(-0.54,16),breaks=c(0,5,10,15), expand = c(0,0)) +
  #labs(x="\nEvolution diet",y="Lactate flux (fmol/cell/hr)") +
  xlab("\n")+
  ylab( expression(atop(paste("Lactate flux (fmol/cell * ",hr^{-1},")"))))+
  annotate("text",x=0.5,y=15.5,label="a",size=12,color="black")+
  #annotate("text",x=1.7,y=0.1,label="B",size=12,color="black")+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),panel.background = element_blank(), axis.line = element_line(colour = "black")) +
    theme(legend.key=element_blank(),axis.text.x=element_text(size=34,margin = margin(t = 20, r = 0, b = 0, l = 0)),axis.text.y=element_text(size=34,margin = margin(t = 0, r = 20, b = 0, l = 0)),axis.title=element_text(size=36),legend.text=element_text(size=22),legend.title = element_text(size=34), axis.ticks.y = element_line(color = "black", size = 3), axis.ticks.x = element_line(color = "black", size = 3), axis.ticks.length.x=unit(0.7, "cm"),axis.ticks.length.y=unit(0.7, "cm"), legend.position = "none", panel.border = element_rect(color = "black", fill = NA, size = 3.5), axis.line = element_line(colour = "black"))
hplclactpanel_F

hplcaceplot_F <- ggplot(hplcdataF, aes(x=evo_trt_plotting, y=flux.ace.0))
###
hplcacepanel_F <- hplcaceplot_F + geom_jitter(aes(shape = evo_trt_plotting, color = evo_trt_plotting), position = position_jitterdodge(jitter.width = 0.8, dodge.width = 0.7), size = 5.5, stroke = 2) +
  #geom_errorbar(data=grcvdataF, mapping = aes(x=carbon.tech.evo,ymin=umax.anc,ymax=umax.anc),color=grcv.colors,lwd=2.2,linetype=117) +
  geom_hline(yintercept = mean(filter(myhplc, condition_short=="F", evo_trt_plotting=="Ancestor")$flux.ace.0), color="dark grey", lwd=2.2,linetype=117) +
  scale_shape_manual(values = c(0,0,0)) +#12 is a square with a vertical cross inside it
      stat_summary(
    aes(color = evo_trt_plotting),
    fun.data = "mean_se", fun.args = list(mult = (0)), #mean_sdl add +/- standard deviation; mult=1 means that it is SD*1 that is drawn.  Mean_se draws the standard error of the mean
    geom = "point", size = 10, stroke=2, shape=16,
    position = position_dodge(1),
  ) +
  stat_summary(
    aes(color = evo_trt_plotting),
    fun.data = "mean_se", fun.args = list(mult = (1)), #mean_sdl add +/- standard deviation; mult=1 means that it is SD*1 that is drawn.  Mean_se draws the standard error of the mean
    geom = "linerange", size = 3,
    position = position_dodge(1),
  ) +
  scale_color_manual(values = mycols_breakout) +
  scale_y_continuous(limits = c(-0.54,28.4),breaks=c(0,5,10,15,20,25), expand = c(0,0)) +
  labs(x="\nEvolution diet",y="Acetate flux (fmol/cell/hr)") +
  xlab("\n")+
  ylab( expression(atop(paste("Acetate flux (fmol/cell * ",hr^{-1},")"))))+
  annotate("text",x=0.5,y=27.3,label="b",size=12,color="black")+
  #annotate("text",x=1.7,y=0.1,label="B",size=12,color="black")+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),panel.background = element_blank(), axis.line = element_line(colour = "black")) +
    theme(legend.key=element_blank(),axis.text.x=element_text(size=34,margin = margin(t = 20, r = 0, b = 0, l = 0)),axis.text.y=element_text(size=34,margin = margin(t = 0, r = 20, b = 0, l = 0)),axis.title=element_text(size=36),legend.text=element_text(size=22),legend.title = element_text(size=34), axis.ticks.y = element_line(color = "black", size = 3), axis.ticks.x = element_line(color = "black", size = 3), axis.ticks.length.x=unit(0.7, "cm"),axis.ticks.length.y=unit(0.7, "cm"), legend.position = "none", panel.border = element_rect(color = "black", fill = NA, size = 3.5), axis.line = element_line(colour = "black"))
hplcacepanel_F

grid.arrange(hplclactpanel_F,hplcacepanel_F,nrow=1)



# Now fructose

fig2.10cols<-c("darkgrey","darkgrey","darkgrey","darkgrey","darkgrey","darkgrey","darkgrey","darkgrey","darkgrey","darkgrey","darkgrey","darkgrey","darkgrey","darkgrey","darkgrey","darkgrey","darkgrey","darkgrey","darkgrey","darkgrey","darkgrey","darkgrey","darkgrey","darkgrey")

fig2.10df<-filter(myhplc, condition_short=="F" & evo_trt_plotting!="Ancestor")

fig2.10plot <- ggplot(fig2.10df, aes(x=evo_trt_plotting, y=flux.fru.pos))
hplcfrupanel_F <- fig2.10plot + geom_jitter(
  aes(shape = evo_trt_plotting, color = evo_trt_plotting),
  position = position_jitterdodge(jitter.width = 1.5, dodge.width = 0.7),
  size = 5.5, stroke = 2) +
  #geom_errorbar(data=grcvdataF, mapping = aes(x=carbon.tech.evo,ymin=umax.anc,ymax=umax.anc),color=grcv.colors,lwd=2.2,linetype=117) +
  geom_hline(yintercept = mean(filter(myhplc, condition_short=="F" & evo_trt_plotting=="Ancestor")$flux.fru.pos), color="dark grey", lwd=2.2,linetype=117) +
  scale_shape_manual(values = c(0,0,0)) +#12 is a square with a vertical cross inside it
    stat_summary(
    aes(color = evo_trt_plotting),
    fun.data = "mean_se", fun.args = list(mult = (0)), #mean_sdl add +/- standard deviation; mult=1 means that it is SD*1 that is drawn.  Mean_se draws the standard error of the mean
    geom = "point", size = 10, stroke=2, shape=16,
    position = position_dodge(1),
  ) +
  stat_summary(
    aes(color = evo_trt_plotting),
    fun.data = "mean_se", fun.args = list(mult = (1)), #mean_sdl add +/- standard deviation; mult=1 means that it is SD*1 that is drawn.  Mean_se draws the standard error of the mean
    geom = "linerange", size = 3,
    position = position_dodge(1),
  ) +
  
  scale_color_manual(values = mycols_breakout) +
  scale_y_continuous(limits = c(-0.54,19),breaks=c(0,5,10,15), expand = c(0,0)) +
  #labs(x="\nEvolution diet",y="Fructose flux (fmol/cell/hr)") +
  xlab("\nEvolution diet")+
  ylab( expression(atop(paste("Fructose flux (fmol/cell * ",hr^{-1},")"))))+
  annotate("text",x=0.5,y=18.4,label="c",size=12,color="black")+
  annotate("text",x=0.7,y=13.5,label="A",size=12,color="black")+
  annotate("text",x=1.7,y=9.0,label="B",size=12,color="black")+
  annotate("text",x=2.7,y=11.4,label="A,B",size=12,color="black")+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),panel.background = element_blank(), axis.line = element_line(colour = "black")) +
    theme(legend.key=element_blank(),axis.text.x=element_text(size=34,margin = margin(t = 20, r = 0, b = 0, l = 0)),axis.text.y=element_text(size=34,margin = margin(t = 0, r = 20, b = 0, l = 0)),axis.title=element_text(size=36),legend.text=element_text(size=22),legend.title = element_text(size=34), axis.ticks.y = element_line(color = "black", size = 3), axis.ticks.x = element_line(color = "black", size = 3), axis.ticks.length.x=unit(0.7, "cm"),axis.ticks.length.y=unit(0.7, "cm"), legend.position = "none", panel.border = element_rect(color = "black", fill = NA, size = 3.5), axis.line = element_line(colour = "black"))

savetofile<-grid.arrange(hplclactpanel_F,hplcacepanel_F,hplcfrupanel_F,nrow=3)
ggsave(plot=savetofile,filename="./Figures/Fig.4.png",width=3000,height=8500,units="px",limitsize=FALSE)
```