---
title: "Evolution of the minimal cell"
author: "Roy Moger-Reischer and Jay T. Lennon"
date: "`r format(Sys.time(), '%d %B, %Y')`"
header-includes:
   - \usepackage{array}
output: pdf_document
geometry: margin=2.54cm
---

# Making Figure 3: ordination of mutated genes

# Clear workspace and set directory
```{r setup}
rm(list=ls())
getwd()
setwd("~/GitHub/MinimalCell")
```

# Load packages and functions
```{r}
require("png")
require("dplyr")
require("grid")
require("vegan")
```

# Load data
```{r}
# Load data
#g.essent.raw <- read.csv("~/GitHub/Bifidobacterium/Pipeline/3_Python/Bifidobacterium_labels_gxp.csv")
g.essent.raw <- read.csv("~/GitHub/Bifidobacterium/Pipeline/3_Python/Bifidobacterium_labels_gxp_fixed.only.csv")
g.essent.raw$sample <- as.factor(g.essent.raw$sample)
g.essent.raw$treatment <- as.factor(g.essent.raw$treatment)
levels(g.essent.raw$treatment)[levels(g.essent.raw$treatment)=="F"] <- "F"
levels(g.essent.raw$treatment)[levels(g.essent.raw$treatment)=="P"] <- "G-F5"
levels(g.essent.raw$treatment)[levels(g.essent.raw$treatment)=="X"] <- "G-F24"
g.essent <- as_tibble(g.essent.raw)
g.essent <- as.matrix(g.essent[,3:ncol(g.essent)])
```

# Permutational mulivariate analyis of variance (PERMANOVA)
```{r}
g.essent.adonis <- adonis(g.essent ~ g.essent.raw$treatment, method = "bray", permutations = 9999)

                       #Df SumsOfSqs MeanSqs F.Model      R2 Pr(>F)    
#g.essent.raw$treatment  2    1.4069 0.70347  2.5781 0.19713  8e-04 ***
#Residuals              21    5.7303 0.27287         0.80287           
#Total                  23    7.1372                 1.00000     
# (same qualitative result with jaccard, canberra, gower, horn, and Kulczynski)
```

# Principal Coordinates Analysis (PCoA)
```{r}
# Create a distance matrix
g.essent.dist <- vegdist(g.essent, method = 'bray', upper = TRUE, diag = TRUE)
g.essent.dist <- as_tibble(data.matrix(g.essent.dist))

# Run PCoA and quantify explained variance
pcoa.eig <- cmdscale(g.essent.dist, eig = TRUE, k = 3)
explainvar1 <- round(pcoa.eig$eig[1] / sum(pcoa.eig$eig), 3) * 100 # 26.9 %
explainvar2 <- round(pcoa.eig$eig[2] / sum(pcoa.eig$eig), 3) * 100 # 14.7 %
explainvar3 <- round(pcoa.eig$eig[3] / sum(pcoa.eig$eig), 3) * 100 # 12.7 %
sum.eig <- sum(explainvar1, explainvar2, explainvar3) # 54 %

# Add sample and treatment IDs
g.essent.pcoa <- as.data.frame(pcoa.eig[1])
g.essent.pcoa$treatment <- g.essent.raw$treatment
row.names(g.essent.pcoa) <- g.essent.raw$sample
g.essent.pcoa$sample <- g.essent.raw$sample
names(g.essent.pcoa)[1:3] <- c('PCo1', 'PCo2', 'PCo3')

gd <- vegdist(g.essent, method = 'bray', upper = TRUE, diag = TRUE)
compare.variance <- betadisper(d=gd, group = c("F","F","F","F","F","F","F","F","G-F5","G-F5","G-F5","G-F5","G-F5","G-F5","G-F5","G-F5","G-F24","G-F24","G-F24","G-F24","G-F24","G-F24","G-F24","G-F24"))
c.v.result <- anova(compare.variance)
TukeyHSD(compare.variance)
###No significant difference in the amount of variance, i.e. beta diversity, among the treatments.
```

# PCoA Plot
```{r, results = "hide"}
png(filename="~/GitHub/Bifidobacterium/Pipeline/3_Python/pcoa.test2_fixed.only.png",
    width = 1200, height = 1200, res = 96*2) 

plot.new()
par(mar = c(7, 7, 5, 7))

plot(g.essent.pcoa[ ,1], g.essent.pcoa[ ,2],
     ylim = c(-.75, .75), xlim = c(-0.75, 0.75),
     xlab = "", ylab = "", xaxt = "n", yaxt = "n",
     pch = 22, cex = 2.0, type = "n", cex.lab = 1.5, cex.axis = 1,
     axes = FALSE)

# Add axes
axis(side = 2, lwd.ticks = 2, cex.axis = 1.25, las = 1,
     labels = c("-1.0", "-0.5", "0.0", "0.5", "1.0"), at = c(-1, -0.5, 0, 0.5, 1))
axis(side = 4, lwd.ticks = 2, cex.axis = 1.25, las = 1,
     at=c(-1, -0.5, 0, 0.5, 1), labels = F)
axis(side = 1, lwd.ticks = 2, cex.axis = 1.25, las = 1,
     labels = c("-0.5", "0.0", "0.5"), at = c(-0.5, 0, 0.5))
axis(side = 3, lwd.ticks = 2, cex.axis = 1.25, las = 1,
     at = c(-0.5, 0, 0.5), labels = F)
abline(h = 0, v = 0, lty = 3)
box(lwd = 2)

# Add axis labels
mtext(expression(paste("PCo 1 (25.0 %)", sep = "")), side = 1,
      outer = TRUE, cex = 1.5, line = -3.0)
mtext(expression(paste("PCo 2 (14.1 %)", sep = "")), side = 2,
      outer = TRUE, cex = 1.5, line = -3.0)

# Add ellipses col = c("blue","red","dark grey"), 
ordiellipse(cbind(g.essent.pcoa$PCo1, g.essent.pcoa$PCo2), groups=g.essent.pcoa$treatment, 
            kind = "sd", conf = 0.95, lwd = 2, lty = 3, draw = "lines", 
            col = c("blue","red","dark grey"), label = TRUE)

# Subset PCoA scores by strain
essent.F <- g.essent.pcoa[which(g.essent.pcoa$treatment == "F"), ]
essent.P <- g.essent.pcoa[which(g.essent.pcoa$treatment == "G-F5"), ]
essent.X <- g.essent.pcoa[which(g.essent.pcoa$treatment == "G-F24"), ]

# Plot points by strain
points(essent.F[ ,1], essent.F[ ,2], pch = 21,
       cex = 2, col = "blue", bg = "blue", lwd = 2)

points(essent.P[ ,1], essent.P[ ,2], pch = 21,
       cex = 2, col = "red", bg = "red", lwd = 2)   

points(essent.X[ ,1], essent.X[ ,2], pch = 21,
       cex = 2, col = "dark grey", bg = "dark grey", lwd = 2)   

# Add P-value associated with PERMANOVA
mtext(expression(~italic("P")~"= 0.0003"), line = -1.75, cex = 1.0, at = -0.4)

# Add treatment labels
#mtext("F", line = -19, cex = 1.2, at = -0.3)
#mtext("G-F5", line = -19, cex = 1.2, at = 0.3)
#mtext("G-F24", line = -19, cex = 1.2, at = 0.3)

# Close Plot Device
dev.off()
graphics.off()

# Show Plot
img <- readPNG("~/GitHub/Bifidobacterium/Pipeline/3_Python/pcoa.test2_fixed.only.png")
grid.raster(img)
```